image: python

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - python -v

  test-count:
    stage: test
    script:
      - python sum.py

  deploy-job:
    stage: deploy
    script:
      - echo "Pipeline Finalizada"